### ISSUE TITLE
[Feat] 가이드 화면 및 승차권 확인 화면

### ISSUE THREAD

**Issue by chaentopia** [HapdongSeminarApp4/iOS_KorailTalk#2]
## 🛠 Issue

내일로 안내 화면 및 승차권 확인 화면

## 📝 To-do

- [ ] 내일로 안내 화면 ui 구현
- [ ] 안내 화면 버튼 함수 추가
- [ ] 승차권 확인 화면 ui 구현
- [ ] 탑승권 뷰 구현
